### ISSUE TITLE
Responsive Behaviour re Donate Banner

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/creativecommons.org#296] opened 2016-06-23 17:04 UTC
When I visit https://creativecommons.org on iPhone 6S , I can scroll on the right hand margin in a way that seems to indicate that the Donate banner is not truly responsive. I'm guessing some of our last commits, intended to address the clarity of the heart image made the donate button poke out?

![img_2127](https://cloud.githubusercontent.com/assets/6674702/16311993/93522214-3927-11e6-9055-be791d5c45b2.jpg)

@mattl , please assign to @DylanMcCall

**Comment by DylanMcCall** [comment] 2016-06-23 17:52
This is a duplicate of issue #287, which is fixed in production although you may need to clear your cache to see.

**Closed** 2016-07-06 19:02 UTC
