### ISSUE TITLE
broken link in license (Dutch)

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#878] opened 2018-10-01 18:38 UTC
From info@ 

  | Legal code missing.  At https://creativecommons.org/licenses/by/3.0/nl/, the link to the legal code from the word "licentie" points to https://creativecommons.org/licenses/by/3.0/nl/legalcode.nl - which responds with 404 Not Found error.
-- | --

**Comment by mzeinstra** [comment] 2019-07-31 14:15
duplicate of #54

**Comment by kgodey** [comment] 2019-08-01 17:28
Closing this, updates will be posted in #54. Thanks @mzeinstra.

**Closed by kgodey** 2019-08-01 17:28 UTC
Labels: legalcode, licenses
