### ISSUE TITLE
Close button on Email Popup is borking for some users

### ISSUE THREAD

**Issue by little-wow** [creativecommons/creativecommons.org#633] opened 2017-06-23 15:18 UTC
Close button on email list popup is borking for some users, see:
https://twitter.com/anthonyhobday/status/878269578966519809
http://d.pr/v/JPPBR4

Tested on Iphone 6S in Safari and worked, Tested on Google Chrome and worked, but users are seeing the issue even with latest Google Chrome.

**Comment by pa-w** [comment] 2017-06-23 15:23
This is how it looks in latest Safari but I could dismiss the modal dialog.
<img width="1102" alt="screen shot 2017-06-23 at 11 21 06 am" src="https://user-images.githubusercontent.com/7355017/27488736-1c096aba-5806-11e7-978f-fa5e8827e9ff.png">

**Comment by robmyers** [comment] 2017-06-23 16:18
I made a change around 8:30am PST that should fix this.

Let me know if anyone is still seeing it.

What happened is that in moving the script into the template for every page I moved it after all our other scripts and that caused this effect (I think). I placed it higher in the template to address this.

**Comment by robmyers** [comment] 2017-06-23 18:18
No it wasn't entirely fixed.

I managed to get it to break on iPad Mini 3 with iOS 8 / Safari.

I've now fixed it for that.

If we still see breakage there's one more thing I can try then we may have to consider pulling it for now if it's still affecting people.

**Comment by mmoreshead** [comment] 2017-06-28 20:51
Got an email from a user today who can't get it to close even after subscribing. He was using firefox 54.4.

**Comment by robmyers** [comment] 2017-06-28 23:39
Cannot reproduce under firefox 54.0 on Windows 10 or macOS Sierra.

I cannot find a firefox 54.4, only a 54.0 beta 4 .

Can the user provide more details about the platform they are on and where they got their version of firefox on?

I'm sorry I can't be more help at this point. :-(

**Comment by mmoreshead** [comment] 2017-06-29 14:27
He sent me a screenshot but I can't seem to pull it from freshdesk.

**Comment by robmyers** [comment] 2017-06-29 16:08
Oh pm me the ticket?

**Closed** 2017-07-11 20:40 UTC
