### ISSUE TITLE
faulty link from NL legalcode

### ISSUE THREAD

**Issue by RCEurope1** [creativecommons/creativecommons.org#51] opened 2015-03-30 18:55 UTC
The link "Terug naar de Commons Deed" ("Back to the Commons Deed") at the bottom of - at least - the Dutch BY-SA 4.0 (http://creativecommons.org/licenses/by-sa/4.0/nl/legalcode) produces an error because it contains one "nl" too much:

http://creativecommons.org/licenses/by-sa/4.0/nl/deed.nl

**Comment by mattl** [comment] 2015-03-30 19:00
Duplicate of #47

**Closed by mattl** 2015-03-30 19:00 UTC
Labels: duplicate
