### ISSUE TITLE
Russian translation dissapearing from Transifex

### ISSUE THREAD

**Issue by georgehari** [creativecommons/creativecommons.org#917] opened 2019-02-07 15:55 UTC
Here is an issue described by a dedicated Transifex collaborator for Russian:

"I'm an employee (content manager and translator in the CC Russia project) of the Institute of the Information Society (Russia's CC affiliate in 2010-2018) and also a long-term volunteer in CC and relevant free-content projects. By the way the Institute as a private NGO has financial problems and I am on vacation. I have just realized that 100%-completed Russian translation of Deeds & Choosers is disappeared again. Can you restore it? Or it seems I have the old *.po file with translation. I'm going to find it and restore translation. I did it many times. Why do these translations disappear again and again? I was OK to be an ordinary translator here on transifex. But nobody reviewed translations and notified about untranslated texts. And it seems nobody translates Deeds & Choosers except me. Can I become a language coordinator here on transifex?"

Any thoughts about this?

@sarahpearson @peterspdx

**Comment by kgodey** [comment] 2019-02-12 20:58
Assigning to Sarah to gather more info, we will triage afterwards.

**Comment by sarahpearson** [comment] 2019-02-12 20:58
@georgehari Do you think the problem is just that the language coordinator for Russian hasn't approved the translation? If so, please go ahead and grant the approval to make this translation live. Or is the problem something bigger?

**Comment by georgehari** [comment] 2019-02-14 10:39
I'm not sure what the problem is, it seems like a human error. Anyway, I made the user language coordinator, so he can review the new translation.

**Comment by kgodey** [comment] 2019-02-14 17:04
It doesn't seem like there's anything for tech to do here so I'll close this ticket.

**Closed by kgodey** 2019-02-14 17:04 UTC
