### ISSUE TITLE
Don't load translated deeds

### ISSUE THREAD

**Issue by rizomaa** [creativecommons/creativecommons.org#469] opened 2016-09-30 14:21 UTC
I would like to upload Belarusian language deeds, but it does not work.

Please:
1. Go here https://creativecommons.org/choose/?lang=be
2. Please choose the link on the page and click "Пазначэнне аўтарства 4.0 Міжнародны"
3. The loaded page is not in belarusian but english https://creativecommons.org/licenses/by/4.0/
   browser:

Firefox 49.0
https://aboutmybrowser.com/EOKeAyUZ

This issue for @robmyers

**Comment by mzeinstra** [comment] 2016-10-05 09:28
I believe what @rizomaa is saying is that the link to a deed should follow the language that is chosen at the chooser. So if I use the Dutch chooser I should get a link to a Dutch deed page in the html, not the generic link.

**Comment by rizomaa** [comment] 2016-10-05 14:13
@mzeinstra thanks

yes, the main issue that it is not only for the belarusian translation but others.

**Comment by robmyers** [comment] 2016-10-05 16:23
I agree it should go to the correct language version.

I am away for a couple of days but I'll take a look at this next week when I get back.

Thank you for reporting this!

**Comment by rizomaa** [comment] 2016-10-16 19:58
Hello,

Any news in the direction?

**Comment by peterspdx** [comment] 2016-12-16 18:51
whoops, closing was unintentional!

**Comment by rizomaa** [comment] 2016-12-17 07:40
@robmyers 

what about the issue?

**Comment by ACEBASS** [comment] 2017-09-22 12:29
That's all I need a if in my software 😑

**Comment by kgodey** [comment] 2019-04-16 20:45
This is a duplicate of #97, closing.

**Closed by kgodey** 2019-04-16 20:45 UTC
Labels: bug, chooser
