### ISSUE TITLE
CC Certificate: Request for Page on certificates.creativecommons.org for pressbooks w/ hypothesis enabled

### ISSUE THREAD

**Issue by jennryn** [creativecommons/creativecommons.org#812] opened 2018-06-07 21:45 UTC
@robmyers:  Can you set up a page on certificates.creativecommons.org for the hypothesis-enabled Pressbooks content by 6/13?

gratefully, 
Jennryn

**Comment by robmyers** [comment] 2018-06-09 01:03
Closing as duplicate of https://certificates.creativecommons.org/cccertedu/

**Closed by robmyers** 2018-06-09 01:03 UTC
