### ISSUE TITLE
Paypal error on donation page for recurring donation

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/creativecommons.org#1078] opened 2020-01-31 21:54 UTC
On this donation page https://us.netdonor.net/page/6650/donate/1/

If you choose "Monthly" and try to pay with Paypal, you get this error:

"PayPal Billing Agreement is required for the PayPal Gateway but was not passed in."

I think this page may help:

https://developer.paypal.com/docs/api/quickstart/create-billing-agreement/

but I can't make sense of it to fix it myself.  

(There's a donor who is requesting that we fix this.)

**Comment by kgodey** [comment] 2020-02-20 00:17
Debugging so far:
I had to add the "PayPal Billing Agreement" field as described here: https://engagingnetworks.support/knowledge-base/pay-via-paypal-recurring-payments/ to the form on the "Donate with aCCelerators" page located here: https://us.e-activist.com/index.html#pages. I added it as a hidden field.

Now I'm getting a different error, "This transaction has failed as there has been an error in processing your payment."

**Comment by kgodey** [comment] 2020-02-20 00:35
@mmoreshead I think I need access to our Paypal account.

**Comment by mmoreshead** [comment] 2020-02-20 18:05
Maybe we can do a thing where we're on a hangout and I screenshare?

**Comment by kgodey** [comment] 2020-02-20 18:27
@mmoreshead I'm not sure that will work, I don't even know what exactly I'm looking for or where it is, I need to poke around to find the developer-focused logs that PayPal is getting from Engaging Networks.

**Comment by mmoreshead** [comment] 2020-02-20 18:34
Ok, once I confirm it's ok with Whitney I'll figure out how to share on lastpass.

**Comment by kgodey** [comment] 2020-02-21 20:25
thanks @mmoreshead

**Comment by kgodey** [comment] 2020-02-27 00:19
@mmoreshead any update here?

**Comment by kgodey** [comment] 2020-07-27 21:19
@mmoreshead I lost track of this issue, I tried debugging this one again and I don't even see a PayPal option on the donate form anymore. Should I close this issue?

**Comment by mmoreshead** [comment] 2020-07-27 21:25
Paypal is still an option on the donate page (you don't get it until half way through the process). I'll leave it to Jami and Moumita to decide if this is important or not. 

All I know is, yes we still take paypal but you can't currently set up a recurring monthly donation that comes from one's paypal account. I also know that we are moving to classy now and not sure if that possibly solves this or not.

**Comment by kgodey** [comment] 2020-07-27 21:31
@mmoreshead it used to be an option on step 2 but now I only see a credit card processing form, no PayPal. I'll follow up with Jami and Moumita.

Moving to Classy might fix this because the problem is on Engaging Networks.

**Comment by kgodey** [comment] 2020-07-27 21:31
@mmoreshead never mind, I found the PayPal option.

**Comment by kgodey** [comment] 2020-07-27 21:35
@mmoreshead I can't view the PayPal password on LastPass so I can't sign in, could you allow me to view the password when you share it? thanks!

**Comment by kgodey** [comment] 2020-07-27 21:40
Debugging notes for myself:

Error according to EN's failed transaction log is:
> 11452: Merchant not enabled for reference transactions

It looks like I'll need to enable stuff in our PayPal account to get it to work.

**Comment by kgodey** [comment] 2020-07-28 18:33
I have access to the PayPal creds in LastPass now, but the password isn't working and I still can't sign in. @mmoreshead is investigating, will leave in "waiting for third-party" until she gets back to me.

**Comment by kgodey** [comment] 2020-10-23 16:54
I'm closing this since we're moving to Classy.

**Closed by kgodey** 2020-10-23 16:54 UTC
